{
	"version": 1674528671,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"9patch.png",
		"untitled90png-sheet0.png",
		"untitled90png-sheet1.png",
		"sprite-sheet0.png",
		"9patch2.png",
		"9patch3.png",
		"untitled9recovered-sheet0.png",
		"9patch4.png",
		"sprite2-sheet0.png",
		"sprite3-sheet0.png",
		"sprite4-sheet0.png",
		"sprite6-sheet0.png",
		"9patch5.png",
		"9patch6.png",
		"9patch7.png",
		"bb-sheet0.png",
		"untitled14lo-sheet0.png",
		"untitle0d09recovered-sheet0.png",
		"construct-sheet0.png",
		"0_-sheet0.png",
		"0_-sheet1.png",
		"0_-sheet2.png",
		"sprite7-sheet0.png",
		"sprite8-sheet0.png",
		"untitled0009recovered-sheet0.png",
		"untitled0009recovered-sheet1.png",
		"9patch8.png",
		"tiledbackground.png",
		"sprite10-sheet0.png",
		"update-sheet0.png",
		"9patch10-sheet0.png",
		"9patc66686h-sheet0.png",
		"9patc986809h-sheet0.png",
		"sprite11-sheet0.png",
		"sprite12-sheet0.png",
		"9patkkkkch-sheet0.png",
		"ikojo-sheet0.png",
		"9patch11-sheet0.png",
		"9patch12.png",
		"sprite13-sheet0.png",
		"fyy-sheet0.png",
		"untitledmojg-sheet0.png",
		"untitledmojg-sheet1.png",
		"sprite14-sheet0.png",
		"windows unlock.m4a",
		"windows unlock.ogg",
		"windows startup.m4a",
		"windows startup.ogg",
		"windows hardware fail.m4a",
		"windows hardware fail.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png",
		"be.png",
		"a.webm",
		"a1.webm",
		"b.webm",
		"a2.webm",
		"n.ico",
		"iransansweb_medium.woff",
		"c2mp-net.js",
		"c2mp-peer.js",
		"c2mp.js",
		"waker.js",
		"push.js",
		"icon.png",
		"firebase.js"
	]
}